Added 30 sec a wait loop in the restart command
If the frontend/factory is not shut down it waits up to 30 sec
(checking every sec). A failure message is printed if shutdown
failed and no start is attempted

diff --git a/creation/templates/factory_initd_startup_template b/creation/templates/factory_initd_startup_template
--- a/creation/templates/factory_initd_startup_template
+++ b/creation/templates/factory_initd_startup_template
@@ -4,14 +4,12 @@
 # description: Starts and stops a glideinWMS factory
 
 # Emulate function library.
-success()
-{
+success() {
     echo -en "\\033[60G[\033[32mOK\033[0m]"
     return 0
 }
 
-failure()
-{
+failure() {
     echo -en "\\033[60G[\033[31mFAILED\033[0m]"
     return 1
 }
@@ -28,8 +26,7 @@ glidein_name=`awk '/^GlideinName /{print $2}' ${factory_dir}/glidein.descript`
 id_str="$glidein_name@${factory_name}"
 
 
-start()
-{
+start() {
     cwd=`pwd`
     cd $factory_dir
     echo -n "Starting glideinWMS factory $id_str: "
@@ -43,20 +40,35 @@ start()
     echo
 }
 
-stop()
-{
+stop() {
     echo -n "Shutting down glideinWMS factory $id_str: "
     "$glideinWMS_dir/factory/stopFactory.py" "$factory_dir" 2>/dev/null 1>&2 </dev/null && success || failure
     RETVAL=$?
     echo
 }
 
-restart()
-{
+restart() {
     stop
     if [ $RETVAL -ne 0 ]; then
+        # Waiting 30 sec for the shutdown to complete
+        echo "Waiting for the glideinWMS factory to shutdown" 2>&1
+        for i in range(60); do
+            # Returns 0 if running, 1 if not
+            "$glideinWMS_dir/factory/checkFactory.py" "$factory_dir" >/dev/null 2>&1 </dev/null
+            if [ $? -eq 1 ]; then
+                RETVAL=0
+                break
+            fi
+            sleep 1
+            echo -n "."
+        done
+        echo
+    fi
+    if [ $RETVAL -ne 0 ]; then
+        echo "Failed to shutdown the glidinWMS factory. Please check."
         exit $RETVAL
     fi
+    echo "Shutdown complete"
     start
 }
 
@@ -172,8 +184,7 @@ upgrade() {
         fi
 }
 
-downtime()
-{
+downtime() {
     if [ -z "$3" ]; then
         echo $"Usage: factory_startup $1 -entry \'factory\'|\'entries\'|entry_name [-delay delay] [-frontend sec_name] [-security sec_class|\'All\'] [-comment comment]"
         exit 1
diff --git a/creation/templates/frontend_initd_startup_template b/creation/templates/frontend_initd_startup_template
--- a/creation/templates/frontend_initd_startup_template
+++ b/creation/templates/frontend_initd_startup_template
@@ -38,16 +38,33 @@ start() {
         
 stop() {
         echo -n "Shutting down glideinWMS frontend $id_str: "
-        "$glideinWMS_dir/frontend/stopFrontend.py" "$frontend_dir" 2>/dev/null 1>&2 </dev/null && success || failure
-        RETVAL=$?
-        echo
+        "$glideinWMS_dir/frontend/stopFrontend.py" -f "$frontend_dir" 2>/dev/null 1>&2 </dev/null && success || failure
+        RETVAL=$? 
+        echo 
 }
         
 restart() {
         stop
         if [ $RETVAL -ne 0 ]; then
+            # Waiting 30 sec for the shutdown to complete
+            echo "Waiting for the glideinWMS frontend to shutdown" 2>&1
+            for i in range(60); do
+                # Returns 0 if running, 1 if not
+                "$glideinWMS_dir/frontend/checkFrontend.py" "$frontend_dir" >/dev/null 2>&1 </dev/null
+                if [ $? -eq 1 ]; then
+                    RETVAL=0
+                    break
+                fi
+                sleep 1
+                echo -n "."
+            done
+            echo
+        fi
+        if [ $RETVAL -ne 0 ]; then
+          echo "Failed to stop the glidinWMS factory. Please check."
           exit $RETVAL
         fi
+        echo "Shutdown complete"
         start
 }
 
