final cleanup 1

diff --git a/creation/templates/factory_initd_startup_template_sl7 b/creation/templates/factory_initd_startup_template_sl7
--- a/creation/templates/factory_initd_startup_template_sl7
+++ b/creation/templates/factory_initd_startup_template_sl7
@@ -395,11 +395,15 @@ reconfig() {
         "$FACTORY_CHECK" "$factory_dir" >/dev/null 2>&1 </dev/null
         notrun=$?
         if [ $notrun -eq 0 ]; then
-            stop
-            if [ $RETVAL -ne 0 ] && [ $RETVAL -ne 2 ]; then
-                echo "Failed to shutdown the GlidinWMS Factory. Please check."
-                exit $RETVAL
-            fi
+            echo "the GlidinWMS Factory is running."
+            echo "You should use reconfig only when Factory is not running"
+            echo "Please stop it first, this script errors out here"
+            exit 1
+#            stop
+#            if [ $RETVAL -ne 0 ] && [ $RETVAL -ne 2 ]; then
+#                echo "Failed to shutdown the GlidinWMS Factory. Please check."
+#                exit $RETVAL
+#            fi
         fi
 
         echo -n "Reconfiguring the factory"
@@ -417,23 +421,6 @@ reconfig() {
         # To return the correct exit code (RET_NOT_CONFIGURED instead of 1)
         [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
         echo
-        if [ $notrun -eq 0 ]; then
-            if [ $reconfig_failed -ne 0 ];then
-                echo ".. starting factory with old configuration file"
-            fi
-            start
-            # At the end RETVAL needs to be set to the value to return
-            # start is changing the value of RETVAL (0-succeded, !0-failed)
-            # reconfig_failed is the reconfiguration result: 0-succeded, !0-failed
-            #  If start failed, then RETVAL=1 (generic error)
-            #  If start succeeded but reconfig failed RETVAL=6 (RET_NOT_CONFIGURED: bad or missing configuration)
-            #  If start succeded and reconfig succeded, then return 0
-            if [ $RETVAL -eq 0 ]; then
-                [ $reconfig_failed -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
-            else
-                RETVAL=1
-            fi
-        fi
 }
 
 upgrade() {
@@ -452,11 +439,10 @@ upgrade() {
         "$FACTORY_CHECK" "$factory_dir" >/dev/null 2>&1 </dev/null
         notrun=$?
         if [ $notrun -eq 0 ]; then
-          stop
-          if [ $RETVAL -ne 0 ] && [ $RETVAL -ne 2 ]; then
-            echo "Failed to shutdown the GlidinWMS Factory. Please check."
-            exit $RETVAL
-          fi
+            echo "the GlidinWMS Factory is running."
+            echo "You should use reconfig only when Factory is not running"
+            echo "Please stop it first, this script errors out here"
+            exit 1
         fi
 
         writeback=$DEFAULT_WRITEBACK
@@ -495,17 +481,6 @@ upgrade() {
         test $reconfig_failed -eq 0 && success || failure
         [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
         echo
-        if [ $notrun -eq 0 ]; then
-          if [ $reconfig_failed -ne 0 ];then
-            echo ".. starting factory with old configuration file"
-          fi
-          start
-          if [ $RETVAL -eq 0 ]; then
-            [ $reconfig_failed -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
-          else
-            RETVAL=1
-          fi
-        fi
 }
 
 downtime() {
