improved exit codes to comply with LSB
Changed the exit codes returned by the init script to comply with LSB recommendations.
Added constants with the exit codes

reconfig and upgrade in frontend/factory were returning:
- stopped, reconfigured and started: 0/0
- reconfigured a stopped service: 0/0
- failed to stop (if initially running): 1/1
- failed to reconfigure (even if started with old configuration): 1/1
- failed to start (after stopping and reconfiguring, even if reconfigure failed): 1/1

The new behavior is similar except:

If not installed (start or check executables missing) fail exit code: 5   (before was 1 because invocation failed)

reconfig and upgrade in frontend/factory are now returning:
- failed to reconfigure (even if started with old configuration): 6/6
- failed to start (after stopping and reconfiguring, even if reconfigure failed): 1/1
To comply with LSB suggestions (1 was OK but 6 is better)

diff --git a/creation/templates/factory_initd_startup_template b/creation/templates/factory_initd_startup_template
--- a/creation/templates/factory_initd_startup_template
+++ b/creation/templates/factory_initd_startup_template
@@ -14,6 +14,42 @@ failure() {
     return 1
 }
 
+# LSB Exit codes for status:
+#0	program is running or service is OK
+#1	program is dead and /var/run pid file exists
+#2	program is dead and /var/lock lock file exists
+#3	program is not running
+#4	program or service status is unknown
+#5-99	reserved for future LSB use
+#100-149	reserved for distribution use
+#150-199	reserved for application use
+#200-254	reserved
+# LSB Exit codes for non status:
+#1	generic or unspecified error (current practice)
+#2	invalid or excess argument(s)
+#3	unimplemented feature (for example, "reload")
+#4	user had insufficient privilege
+#5	program is not installed
+#6	program is not configured
+#7	program is not running
+#8-99	reserved for future LSB use
+#100-149	reserved for distribution use
+#150-199	reserved for application use
+#200-254	reserved
+RET_OK=0
+RET_ERROR=1
+RET_STATUS_DEADWPIDFILE=1
+RET_STATUS_DEADWLOCK=2
+RET_STATUS_NOT_RUNNING=3
+RET_STATUS_UNKNOWN=4
+RET_BAD_SYNTAX=2
+RET_NOT_IMPLEMENTED=3
+RET_NO_PRIVILEGE=4
+RET_NOT_INSTALLED=5
+RET_NOT_CONFIGURED=6
+RET_NOT_RUNNING=7
+
+
 [ -f /etc/sysconfig/gwms-factory ] && . /etc/sysconfig/gwms-factory
 
 # Variables substituted during the file creation (by cgWCreate.py)        
@@ -65,6 +101,15 @@ else
     FACTORY_CONFIG="$factory_dir/glideinWMS.xml"
 fi
 
+check_installed () {
+    # check to see if the program is installed (look for FACTORY_START and FACTORY_CHECK)
+    if [ -x "$FACTORY_START" -a -x "$FACTORY_CHECK" ]; then
+        return 0
+    fi
+    echo -n "The Factory is not installed correctly"
+    failure
+    exit $RET_NOT_INSTALLED
+}
 
 export HOME="/var/lib/gwms-factory"
 export X509_CERT_DIR="/etc/grid-security/certificates"
@@ -73,8 +118,8 @@ FACTORY_USER=gfactory
 
 
 if [ -r "${factory_dir}/glidein.descript" ]; then
-    factory_name=`awk '/^FactoryName /{print $2}' ${factory_dir}/glidein.descript`
-    glidein_name=`awk '/^GlideinName /{print $2}' ${factory_dir}/glidein.descript`
+    factory_name="`awk '/^FactoryName /{print $2}' ${factory_dir}/glidein.descript`"
+    glidein_name="`awk '/^GlideinName /{print $2}' ${factory_dir}/glidein.descript`"
     force_name_option="-force_name \"$glidein_name\""
 else
     factory_name="NEW_INSTALL"
@@ -95,7 +140,7 @@ get_user() {
 }
 
 # Check that factory user is the owner of the config file
-THIS_USER=`get_user`
+THIS_USER="`get_user`"
 THIS_ID=`id -u $THIS_USER`
 # should check actually the config file in the working directory
 # Double percent %% needed for template substitution
@@ -105,13 +150,13 @@ if [ $THIS_ID -eq 0 ]; then
         echo "The Factory user ($FACTORY_USER) must own the configuration file ($def_factory_config).
 Use the correct user or edit FACTORY_USER in $0"
         failure
-        exit 4
+        exit $RET_NO_PRIVILEGE
     fi
 else
     if [ $THIS_ID -ne $FILE_OWNER ]; then
         echo "The user invoking this script ($THIS_ID) must be root or must own the configuration file ($def_factory_config)"
         failure
-        exit 4
+        exit $RET_NO_PRIVILEGE
     fi
 fi
 
@@ -174,6 +219,7 @@ help_usage() {
 }
 
 start() {
+    check_installed
     pushd $factory_dir 1>/dev/null
     echo -n "Starting GlideinWMS Factory $id_str: "
 
@@ -205,6 +251,7 @@ start() {
 }
 
 stop() {
+    check_installed
     echo -n "Shutting down GlideinWMS Factory $id_str: "
 
     "$FACTORY_CHECK" "$factory_dir" 2>/dev/null 1>&2 </dev/null 
@@ -273,15 +320,16 @@ restart() {
 }
 
 reconfig() {
-        shift
-        if [ -f "$1" ]; then
-            echo "Using factory config file arg: $1"
-            cfg_loc=$1
-            shift 
-        else
-            echo "Using default factory config file: $def_factory_config"
-            cfg_loc=$def_factory_config
-        fi
+    check_installed
+    shift
+    if [ -f "$1" ]; then
+        echo "Using factory config file arg: $1"
+        cfg_loc=$1
+        shift 
+    else
+        echo "Using default factory config file: $def_factory_config"
+        cfg_loc=$def_factory_config
+    fi
         update_def_cfg_option=
         update_def_cfg=no
         writeback=$DEFAULT_WRITEBACK
@@ -342,15 +390,15 @@ reconfig() {
         reconfig_failed=$?
         popd 1>/dev/null
         test $reconfig_failed -eq 0 && success || failure
-        RETVAL=$?
+        [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
         echo
         if [ $notrun -eq 0 ]; then
             if [ $reconfig_failed -ne 0 ];then
                 echo ".. starting factory with old configuration file"
             fi
             start
-            if [ $RETVAL -eq 0 ] && [ $reconfig_failed -eq 0 ]; then
-                RETVAL=0
+            if [ $RETVAL -eq 0 ]; then
+                [ $reconfig_failed -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
             else
                 RETVAL=1
             fi
@@ -358,7 +406,8 @@ reconfig() {
 }
 
 upgrade() {
-        shift
+    check_installed
+    shift
         if [ -f "$1" ]; then
            echo "Using factory config file arg: $1"
            cfg_loc=$1
@@ -412,15 +461,15 @@ upgrade() {
         popd 1>/dev/null
         echo -n "Upgrading the factory"
         test $reconfig_failed -eq 0 && success || failure
-        RETVAL=$?
+        [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
         echo
         if [ $notrun -eq 0 ]; then
           if [ $reconfig_failed -ne 0 ];then
             echo ".. starting factory with old configuration file"
           fi
           start
-          if [ $RETVAL -eq 0 ] && [ $reconfig_failed -eq 0 ]; then
-            RETVAL=0
+          if [ $RETVAL -eq 0 ]; then
+            [ $reconfig_failed -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
           else
             RETVAL=1
           fi
@@ -500,7 +549,7 @@ case $1 in
     *)
         help_usage
         #echo $"Usage: factory_startup {start|stop|restart|status|info|reconfig|down|up|infosysdown|statusdown}"
-        exit 3
+        exit $RET_NOT_IMPLEMENTED
 esac
 
 exit $RETVAL
