reconfig and upgrade functions rewritten

diff --git a/creation/templates/frontend_initd_startup_template_sl7 b/creation/templates/frontend_initd_startup_template_sl7
--- a/creation/templates/frontend_initd_startup_template_sl7
+++ b/creation/templates/frontend_initd_startup_template_sl7
@@ -345,103 +345,131 @@ reconfig() {
         #  1 generic error (also start failed) 
         check_installed
         shift
-        if [ -f "$1" ]; then
-            echo "Using Frontend config file arg: $1"
-            cfg_loc=$1
-            shift           
-        else
-            echo "Using default Frontend config file: $def_frontend_config"
-            cfg_loc=$def_frontend_config
-        fi
-        # Set defaults and check if parameters
-        update_def_cfg="no"
-        writeback=$DEFAULT_WRITEBACK
-        fix_rrd=""
-        for var in "$@"
-        do
-            case "$var" in
-            yes | no) writeback="$var"
-                ;;
-            update_default_cfg) update_def_cfg="yes"
-                if [ "$RPM_INSTALL" = "True" ]; then
-                    echo "update_def_cfg is not a valid option for RPM installations"
-                    help_usage
-                    exit 2
-                fi
-                ;;
-            "-fix_rrd") fix_rrd="-fix_rrd"
-                ;;
-            *)  # shift to avoid scanning file: if [ "$cfg_loc" != "$var" ]; then
-                echo "Unknown argument passed: $var"
-                help_usage
-                exit 2
-                #fi
-                ;;
-            esac
-        done
-        if [ -n "$GLIDEIN_WRITEBACK" ]; then
-            writeback="$GLIDEIN_WRITEBACK"
-        fi
 
         "${FRONTEND_CHECK}" "$frontend_dir" >/dev/null 2>&1 </dev/null
-        notrun=$?
-        if [ $notrun -eq 0 ]; then
-            echo "the GlidinWMS Frontend is running."
-            echo "You should use reconfig only when Frontend is not running"
-            echo "Please stop it first using systemctl command, this script errors out here"
-            exit 1
-        fi
-        pushd $frontend_dir 1>/dev/null
+        notrun=$? # 1 = not running
+        if [ $notrun -eq 1 ]; then
+            # If the Frontend not running, we can use the original code from reconfig() 
+            # which allows the users to use the options
+            if [ -f "$1" ]; then
+		echo "Using Frontend config file arg: $1"
+		cfg_loc=$1
+		shift           
+            else
+		echo "Using default Frontend config file: $def_frontend_config"
+		cfg_loc=$def_frontend_config
+            fi
+            # Set defaults and check if parameters
+            update_def_cfg="no"
+            writeback=$DEFAULT_WRITEBACK
+            fix_rrd=""
+            for var in "$@"
+            do
+		case "$var" in
+		    yes | no) writeback="$var"
+			;;
+		    update_default_cfg) update_def_cfg="yes"
+			if [ "$RPM_INSTALL" = "True" ]; then
+			    echo "update_def_cfg is not a valid option for RPM installations"
+			    help_usage
+			    exit 2
+			fi
+			;;
+		    "-fix_rrd") fix_rrd="-fix_rrd"
+			;;
+		    *)  # shift to avoid scanning file: if [ "$cfg_loc" != "$var" ]; then
+			echo "Unknown argument passed: $var"
+			help_usage
+			exit 2
+			;;
+		esac
+            done
 
+            if [ -n "$GLIDEIN_WRITEBACK" ]; then
+		writeback="$GLIDEIN_WRITEBACK"
+            fi
+
+            pushd $frontend_dir 1>/dev/null
         # Defaults of reconfig_frontend (f-flag, v-variable)
         # f   fix_rrd = False
         # v   writeback = 'no'
         # v   update_scripts = 'no'
         # v   update_def_cfg = 'no'
-        invoke_as_frontend "\"${CREATION_DIR}reconfig_frontend\" -force_name \"$frontend_name\" -writeback $writeback -xml \"$cfg_loc\" -update_def_cfg \"$update_def_cfg\" $fix_rrd"
+            invoke_as_frontend "\"${CREATION_DIR}reconfig_frontend\" -force_name \"$frontend_name\" -writeback $writeback -xml \"$cfg_loc\" -update_def_cfg \"$update_def_cfg\" $fix_rrd"
 
-        reconfig_failed=$?
-        popd 1>/dev/null
-        echo -n "Reconfiguring the frontend"
-        test $reconfig_failed -eq 0 && success || failure
-        # To return the correct exit code (RET_NOT_CONFIGURED instead of 1)
-        [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
-        echo
+            reconfig_failed=$?
+            popd 1>/dev/null
+            echo -n "Reconfiguring the frontend"
+            test $reconfig_failed -eq 0 && success || failure
+            # To return the correct exit code (RET_NOT_CONFIGURED instead of 1)
+            [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
+            echo
+
+	else
+	    # Frontend running, we can proceed
+            argno="$#"
+            argnoint=$(( argno + 0 ))
+
+            if [ $argnoint -eq 0 ]; then
+		echo 'no argument: I have to run kill -1 with the frontend PID'
+		killpid=`awk '/PID/ {print $2}' $frontend_dir/lock/frontend.lock`
+		kill -1 $killpid
+            else
+		echo 'If Frontend running and at the same time if you want to use arguments, '
+		echo 'you have to stop Frontend first manually'
+		return 1
+            fi
+        fi
+        return 0
 }
-        
+
 upgrade() {
         # see reconfig for return values and logic explanation
         check_installed
-        if [ -f "$1" ]; then
-            echo "Using frontend config file arg: $1"
-            cfg_loc=$1
-        else
-            echo "Using default frontend config file: $def_frontend_config"
-            cfg_loc=$def_frontend_config
-        fi
-        "$FRONTEND_CHECK" "$frontend_dir" >/dev/null 2>&1 </dev/null
+
+        "${FRONTEND_CHECK}" "$frontend_dir" >/dev/null 2>&1 </dev/null
         notrun=$?
-        if [ $notrun -eq 0 ]; then
-            echo "the GlidinWMS Frontend is running."
-            echo "You should use upgrade only when Frontend is not running"
-            echo "Please stop it first using systemctl command, this script errors out here"
-            exit 1
-        fi
-        pushd $frontend_dir 1>/dev/null
+        if [ $notrun -eq 1 ]; then   # 1 = not running
+            # If the Frontend not running, we can use the original code from reconfig() 
+            # which allows the users to use the options
+            if [ -f "$1" ]; then
+		echo "Using frontend config file arg: $1"
+		cfg_loc=$1
+            else
+		echo "Using default frontend config file: $def_frontend_config"
+		cfg_loc=$def_frontend_config
+            fi
+
+            pushd $frontend_dir 1>/dev/null
 
         # Defaults of reconfig_frontend (f-flag, v-variable)
         # f   fix_rrd = True
         # v   writeback = yes
         # v   update_scripts = yes
         # v   update_def_cfg = no
-        invoke_as_frontend "\"${CREATION_DIR}reconfig_frontend\" -force_name \"$frontend_name\" -writeback yes -update_scripts yes -xml \"$cfg_loc\" -fix_rrd"
+            invoke_as_frontend "\"${CREATION_DIR}reconfig_frontend\" -force_name \"$frontend_name\" -writeback yes -update_scripts yes -xml \"$cfg_loc\" -fix_rrd"
 
-        reconfig_failed=$?
-        popd 1>/dev/null
-        echo -n "Upgrading the frontend"
-        test $reconfig_failed -eq 0 && success || failure
-        [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
-        echo
+            reconfig_failed=$?
+            popd 1>/dev/null
+            echo -n "Upgrading the frontend"
+            test $reconfig_failed -eq 0 && success || failure
+            [ $? -eq 0 ] && RETVAL=0 || RETVAL=$RET_NOT_CONFIGURED
+            echo
+
+	else
+            # Frontend running, we can proceed
+            argno="$#"
+            argnoint=$(( argno + 0 ))
+            if [ $argnoint -eq 0 ]; then
+		killpid=`awk '/PID/ {print $2}' $frontend_dir/lock/frontend.lock`
+		kill -1 $killpid
+            else
+		echo 'If Frontend running and at the same time if you want to use arguments, '
+		echo 'you have to stop Frontend first manually'
+		return 1
+            fi
+        fi
+        return 0
 }
 
 downtime() {
